name: Scheduled Run (Priority)

on:
  schedule:
    - cron: "30 */1 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          repository: ${{ secrets.PRIVATE_REPO }}
          token: ${{ secrets.REPO_PAT }}
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version: 23
          cache: npm
      - name: Cache browsers
        id: browser-cache
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: ~/.cache/ms-playwright
          key: pw-${{ runner.os }}-${{ hashFiles('node_modules/playwright/package.json') }}
      - uses: aws-actions/configure-aws-credentials@ff717079ee2060e4bcee96c4779b553acc87447c # v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
      - run: bash scripts/ci.sh priority > /dev/null 2>&1
        env:
          FARECRAFT_API_URL: ${{ secrets.FARECRAFT_API_URL }}

